const baseURL = import.meta.env.VITE_BASE_URL
export const route = {
  application: {
    getPublishedTerm: `${baseURL}/api/v1/application/find-published-term`,
    createApplicant: `${baseURL}/api/v1/application/create-applicant`,
  },
  admin: {
    changeCurrentTermName: `${baseURL}/api/v1/admin/administration/update/term-name`,
    extendCurrentTerm: `${baseURL}/api/v1/admin/administration/update/extend-term`,
    makeCurrentTerm: `${baseURL}/api/v1/admin/administration/update/make-current-term`,
    makePublishTerm: `${baseURL}/api/v1/admin/administration/update/make-publish-term`,
    unPublishTerm: `${baseURL}/api/v1/admin/administration/update/un-publish-term`,
    createTermWithSubjectsSetup: `${baseURL}/api/v1/admin/administration/create-new-term-setup`,
    findAllTerms: `${baseURL}/api/v1/admin/administration/find-all-terms`,
    findCurrentTerm: `${baseURL}/api/v1/admin/administration/find-current-term`,
    findPublishedTerm: `${baseURL}/api/v1/admin/administration/find-published-term-administration`,
    findUniqueTerm: `${baseURL}/api/v1/admin/administration/find/term-detail`,
    deleteTerm: `${baseURL}/api/v1/admin/administration/delete-term`,
    studentListInATerm: `${baseURL}/api/v1/admin/administration/term-students-list`,
    groups: {
      findAllGroups: `${baseURL}/api/v1/admin/administration/get-all-groups`,
    },
    subject: {
      findAllSubjects: `${baseURL}/api/v1/admin/administration/get-all-subjects`,
    },
    level: {
      findAllLevels: `${baseURL}/api/v1/admin/administration/get-all-levels`,
    },
    class: {
      findCurrentTermForManageClass: `${baseURL}/api/v1/admin/administration/class/find-current-term-manage-class`,
      findCurrentTermClass: `${baseURL}/api/v1/admin/administration/class/find-current-term-class`,
      findPublishTermForManageClass: `${baseURL}/api/v1/admin/administration/class/find-publish-term-manage-class`,
      findSectionsForManageClass: `${baseURL}/api/v1/admin/administration/class/find-sections-manage-class`,
      createClass: `${baseURL}/api/v1/admin/administration/class/create-class`,
    },
    timetable: {
      createTimetable: `${baseURL}/api/v1/admin/timetable/create-new-timetable`,
      updateTimetable: `${baseURL}/api/v1/admin/timetable/update-timetable`,
      findActiveTimetable: `${baseURL}/api/v1/admin/timetable/find-active-timetable`,
    },
  },
  applicantEnrollment: {
    getAllApplicants: `${baseURL}/api/v1/admin/applicant/get-all-applicants`,
    searchApplicants: `${baseURL}/api/v1/admin/applicant/search-applicants`,
    findApplicantById: `${baseURL}/api/v1/admin/applicant/applicant-detail`,
    findTermToEnroll: `${baseURL}/api/v1/admin/applicant/term-to-enroll`,
    findCurrentTermToEnroll: `${baseURL}/api/v1/admin/applicant/current-term-to-enroll`,
    enrollApplicant: `${baseURL}/api/v1/admin/applicant/enroll-applicant`,
    deEnrollApplicant: `${baseURL}/api/v1/admin/applicant/de-enroll-applicant`,
    findApplicantEnrolledSubjects: `${baseURL}/api/v1/admin/applicant/find-enrolled-subjects-applicant`,
    enrollApplicantToStudent: `${baseURL}/api/v1/admin/applicant/enroll-applicant-to-student`,
  },
  enrolledStudents: {
    getAllEnrolledStudents: `${baseURL}/api/v1/admin/student/enrolled/get-all-enrolled-students`,
    searchEnrolledStudents: `${baseURL}/api/v1/admin/student/enrolled/search-enrolled-students`,
    findEnrolledStudentById: `${baseURL}/api/v1/admin/student/enrolled/enrolled-student-detail`,
    findTermToEnrollEnrolledStudent: `${baseURL}/api/v1/admin/student/enrolled/term-to-enroll-student-enrolled`,
    findEnrolledStudentEnrolledSubjects: `${baseURL}/api/v1/admin/student/enrolled/find-enrolled-subjects-for-enrolled-student`,
    enrollEnrolledStudent: `${baseURL}/api/v1/admin/student/enrolled/enroll-enrolled-student`,
    enrollEnrolledStudentToCurrentTerm: `${baseURL}/api/v1/admin/student/enrolled/enrolled-student-to-current-term`,
    deEnrollEnrolledStudent: `${baseURL}/api/v1/admin/student/enrolled/de-enroll-enrolled-student`,
  },
  lateEnrolledStudents: {
    getAllLateEnrolledStudents: `${baseURL}/api/v1/admin/student/late-enrolled/get-all-late-enrolled-students`,
    searchLateEnrolledStudents: `${baseURL}/api/v1/admin/student/late-enrolled/search-all-late-enrolled-students`,
    findLateEnrolledStudentById: `${baseURL}/api/v1/admin/student/late-enrolled/late-enrolled-student-detail`,
    findTermToEnrollLateEnrolledStudent: `${baseURL}/api/v1/admin/student/late-enrolled/term-to-enroll-late-enrolled-student`,
    findLateEnrolledStudentEnrolledSubjects: `${baseURL}/api/v1/admin/student/late-enrolled/find-enrolled-subjects-for-late-enrolled-student`,
    enrollLateEnrolledStudent: `${baseURL}/api/v1/admin/student/late-enrolled/enroll-late-enrolled-student`,
    enrollLateStudentToActive: `${baseURL}/api/v1/admin/student/late-enrolled//enroll-late-enrolled-student-to-active`,
    deEnrollLateEnrolledStudent: `${baseURL}/api/v1/admin/student/late-enrolled/de-enroll-late-enrolled-student`,
  },

  activeStudents: {
    getAllActiveStudents: `${baseURL}/api/v1/admin/student/active/get-all-active-students`,
    searchActiveStudents: `${baseURL}/api/v1/admin/student/active/search-active-students`,
    findActiveStudentById: `${baseURL}/api/v1/admin/student/active/active-student-detail`,
    findActiveStudentFeeDetailsById: `${baseURL}/api/v1/admin/student/active/active-student-fee-detail`,
    findTermSubjectGroupIdEnrolledSubjects: `${baseURL}/api/v1/admin/student/active/find-enrolled-subjects-term-subject-group`,
    findFeePaymentById: `${baseURL}/api/v1/admin/student/active/fee-payment-detail`,
    updateAmountPaid: `${baseURL}/api/v1/admin/student/active/fee-payment-update-amountPaid`,
    findActiveStudentEnrolledSubjects: `${baseURL}/api/v1/admin/student/active/find-enrolled-subjects-active-student`,
    findCurrentTermToAssignClass: `${baseURL}/api/v1/admin/student/active/find-current-term-to-assign-class`,
    assignClassToStudent: `${baseURL}/api/v1/admin/student/active/assign-class-active-student`,
  },
}
//assign-class-active-student